name: Release

on:
  push:
    tags:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Setup cachix
        uses: cachix/cachix-action@v16
        with:
          name: devenv

      - name: Create GitHub release artifacts
        run: nix develop --impure --command goreleaser release --clean --config .goreleaser.release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
