name: Release

on:
  push:
    tags:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Setup cachix
        uses: cachix/cachix-action@v16
        with:
          name: devenv

      - name: Build Python Package
        run: |
          nix develop --impure --command uv build

      - name: Create or Update Tag Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            dist/*.whl
            dist/*.tar.gz
          generate_release_notes: true
